"""update trip23

Revision ID: 143dbd22bcf0
Revises: b3a900cde191
Create Date: 2024-07-12 16:26:41.890141

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '143dbd22bcf0'
down_revision = 'b3a900cde191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('id', sa.int(), nullable=False))
    op.drop_index('ix_trip_trip_id', table_name='trip')
    op.drop_column('trip', 'trip_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('trip_id', sa.int(), autoincrement=True, nullable=False))
    op.create_index('ix_trip_trip_id', 'trip', ['trip_id'], unique=False)
    op.drop_column('trip', 'id')
    # ### end Alembic commands ###
