"""edit trip

Revision ID: 1b249d13e2a2
Revises: 20ed959e67a7
Create Date: 2024-07-13 01:08:19.053525

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1b249d13e2a2'
down_revision = '20ed959e67a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'trip', 'driver', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'trip', 'route', ['route_id'], ['id'])
    op.drop_column('trip', 'wokring_place')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('wokring_place', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_constraint(None, 'trip', type_='foreignkey')
    # ### end Alembic commands ###
