"""edit tripd

Revision ID: 6d717f59ae5a
Revises: 1b249d13e2a2
Create Date: 2024-07-13 01:21:30.520181

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6d717f59ae5a'
down_revision = '1b249d13e2a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
