"""update trip2

Revision ID: e7b94e1341b6
Revises: 92db502277f9
Create Date: 2024-07-12 16:16:03.562577

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e7b94e1341b6'
down_revision = '92db502277f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
