"""car model edit2

Revision ID: f17a696497ad
Revises: fe29d3c886ff
Create Date: 2024-07-12 23:00:29.007431

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f17a696497ad'
down_revision = 'fe29d3c886ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
