"""update trip234

Revision ID: fe29d3c886ff
Revises: 143dbd22bcf0
Create Date: 2024-07-12 16:43:27.166878

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fe29d3c886ff'
down_revision = '143dbd22bcf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
