"""new migration

Revision ID: 01f121153227
Revises: 37a9aef2a1ea
Create Date: 2024-07-17 15:47:04.340623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f121153227'
down_revision: Union[str, None] = '37a9aef2a1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('car_driver_id_key', 'car', type_='unique')
    op.alter_column('trip', 'passenger_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip', 'passenger_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('car_driver_id_key', 'car', ['driver_id'])
    # ### end Alembic commands ###
