"""new migration

Revision ID: 37a9aef2a1ea
Revises: e08216206aa4
Create Date: 2024-07-17 14:26:12.538239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a9aef2a1ea'
down_revision: Union[str, None] = 'e08216206aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'route', ['driver_id'])
    op.create_foreign_key(None, 'route', 'driver', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.drop_constraint(None, 'route', type_='unique')
    op.drop_column('route', 'driver_id')
    # ### end Alembic commands ###
