"""new migration

Revision ID: 437d8e549a50
Revises: 7da6fdd8bdc7
Create Date: 2024-07-17 03:43:32.642548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '437d8e549a50'
down_revision: Union[str, None] = '7da6fdd8bdc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('car_id', sa.Integer(), nullable=True))
    op.drop_constraint('driver_license_number_key', 'driver', type_='unique')
    op.drop_column('trip', 'tripStatus')
    op.drop_column('trip', 'estimation')
    op.drop_column('trip', 'type')
    op.drop_column('trip', 'cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('trip', sa.Column('type', postgresql.ENUM('daily', 'weekly', 'monthly', 'yearly', name='triptype'), autoincrement=False, nullable=True))
    op.add_column('trip', sa.Column('estimation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('trip', sa.Column('tripStatus', postgresql.ENUM('start', 'in_way', 'arrive_you', 'cancelled', 'arrived_destination', name='tripstatus'), autoincrement=False, nullable=True))
    op.create_unique_constraint('driver_license_number_key', 'driver', ['license_number'])
    op.drop_column('driver', 'car_id')
    # ### end Alembic commands ###
