"""new migration

Revision ID: 49f44036951d
Revises: c027f46502e3
Create Date: 2024-07-17 04:34:33.857218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '49f44036951d'
down_revision: Union[str, None] = 'c027f46502e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passenger', sa.Column('type', sa.Enum('mail', 'female', 'mix', name='passengertype'), nullable=True))
    op.add_column('passenger', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('passenger', sa.Column('distination', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('passenger', sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('passenger', sa.Column('pickup_date', sa.DateTime(), nullable=True))
    op.add_column('passenger', sa.Column('pickup_time', sa.DateTime(), nullable=True))
    op.add_column('passenger', sa.Column('pickup_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('passenger', sa.Column('return_date', sa.DateTime(), nullable=True))
    op.add_column('passenger', sa.Column('return_time', sa.DateTime(), nullable=True))
    op.add_column('passenger', sa.Column('service_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passenger', 'service_hours')
    op.drop_column('passenger', 'return_time')
    op.drop_column('passenger', 'return_date')
    op.drop_column('passenger', 'pickup_location')
    op.drop_column('passenger', 'pickup_time')
    op.drop_column('passenger', 'pickup_date')
    op.drop_column('passenger', 'payment_method')
    op.drop_column('passenger', 'distination')
    op.drop_column('passenger', 'location')
    op.drop_column('passenger', 'type')
    # ### end Alembic commands ###
