"""new migration

Revision ID: 580a1e2fc609
Revises: 49f44036951d
Create Date: 2024-07-17 05:09:08.104874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '580a1e2fc609'
down_revision: Union[str, None] = '49f44036951d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'car_id')
    op.add_column('trip', sa.Column('estimation', sa.DateTime(), nullable=True))
    op.add_column('trip', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('trip', sa.Column('tripStatus', sa.Enum('start', 'in_way', 'arrive_you', 'cancelled', 'arrived_destination', name='tripstatus'), nullable=True))
    op.add_column('trip', sa.Column('type', sa.Enum('daily', 'weekly', 'monthly', 'yearly', name='triptype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'type')
    op.drop_column('trip', 'tripStatus')
    op.drop_column('trip', 'cost')
    op.drop_column('trip', 'estimation')
    op.add_column('driver', sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
