"""new migration

Revision ID: 6ff848f0d4f0
Revises: 7c9b1234efeb
Create Date: 2024-07-17 20:50:27.702791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff848f0d4f0'
down_revision: Union[str, None] = '7c9b1234efeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('path', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route', 'path')
    # ### end Alembic commands ###
