"""new migration

Revision ID: 7c9b1234efeb
Revises: 01f121153227
Create Date: 2024-07-17 20:30:08.569704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7c9b1234efeb'
down_revision: Union[str, None] = '01f121153227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('route', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('route', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('route', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('route', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('route', 'start_date')
    op.drop_column('route', 'return_date')
    op.drop_column('route', 'start_location')
    op.drop_column('route', 'distenation')
    op.drop_column('route', 'start_tim')
    op.drop_column('route', 'end_time')
    op.drop_column('route', 'estimated_duration')
    op.add_column('trip', sa.Column('passengers_count', sa.Integer(), nullable=True))
    op.add_column('trip', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('trip', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'updated_at')
    op.drop_column('trip', 'created_at')
    op.drop_column('trip', 'passengers_count')
    op.add_column('route', sa.Column('estimated_duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('route', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('route', sa.Column('start_tim', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('route', sa.Column('distenation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('route', sa.Column('start_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('route', sa.Column('return_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('route', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('route', 'updated_at')
    op.drop_column('route', 'created_at')
    op.drop_column('route', 'address')
    op.drop_column('route', 'longitude')
    op.drop_column('route', 'latitude')
    # ### end Alembic commands ###
