"""new migration

Revision ID: c027f46502e3
Revises: 437d8e549a50
Create Date: 2024-07-17 04:32:39.241622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c027f46502e3'
down_revision: Union[str, None] = '437d8e549a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passenger', 'location')
    op.drop_column('passenger', 'distination')
    op.drop_column('passenger', 'payment_method')
    op.drop_column('passenger', 'pickup_date')
    op.drop_column('passenger', 'pickup_time')
    op.drop_column('passenger', 'pickup_location')
    op.drop_column('passenger', 'service_hours')
    op.drop_column('passenger', 'return_date')
    op.drop_column('passenger', 'type')
    op.drop_column('passenger', 'return_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passenger', sa.Column('return_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('passenger', sa.Column('type', postgresql.ENUM('mail', 'female', 'mix', name='passengertype'), autoincrement=False, nullable=True))
    op.add_column('passenger', sa.Column('return_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('passenger', sa.Column('service_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('passenger', sa.Column('pickup_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('passenger', sa.Column('pickup_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('passenger', sa.Column('pickup_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('passenger', sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('passenger', sa.Column('distination', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('passenger', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
