"""new migration

Revision ID: d987a09a3261
Revises: 6ff848f0d4f0
Create Date: 2024-07-17 20:56:33.547431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd987a09a3261'
down_revision: Union[str, None] = '6ff848f0d4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('driver', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('passenger', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('passenger', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('route', sa.Column('start', sa.Float(), nullable=True))
    op.add_column('route', sa.Column('end', sa.Float(), nullable=True))
    op.drop_column('route', 'latitude')
    op.drop_column('route', 'address')
    op.drop_column('route', 'longitude')
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.add_column('route', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('route', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('route', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('route', 'end')
    op.drop_column('route', 'start')
    op.drop_column('passenger', 'updated_at')
    op.drop_column('passenger', 'created_at')
    op.drop_column('driver', 'updated_at')
    op.drop_column('driver', 'created_at')
    # ### end Alembic commands ###
