"""new migration

Revision ID: e08216206aa4
Revises: 580a1e2fc609
Create Date: 2024-07-17 05:10:42.212365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e08216206aa4'
down_revision: Union[str, None] = '580a1e2fc609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('trip_status', sa.Enum('start', 'in_way', 'arrive_you', 'cancelled', 'arrived_destination', name='tripstatus'), nullable=True))
    op.drop_column('trip', 'tripStatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('tripStatus', postgresql.ENUM('start', 'in_way', 'arrive_you', 'cancelled', 'arrived_destination', name='tripstatus'), autoincrement=False, nullable=True))
    op.drop_column('trip', 'trip_status')
    # ### end Alembic commands ###
